config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    before_action :set_kitten, only: [:show, :edit, :update, :destroy]
  
    def index
      @kittens = Kitten.all

      respond_to do |format|
        format.html # default for the browser's HTML response
        format.json { render json: @kittens } # JSON response
      end  
    end
  
    def show
      respond_to do |format|
        format.html # default for the browser's HTML response
        format.json { render json: @kitten } # JSON response for a single kitten
      end  
    end
  
    def new
      @kitten = Kitten.new
    end
  
    def create
      @kitten = Kitten.new(kitten_params)
      if @kitten.save
        flash[:notice] = "Kitten created successfully!"
        redirect_to @kitten
      else
        flash[:alert] = "There was an error creating the kitten."
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @kitten.update(kitten_params)
        flash[:notice] = "Kitten updated successfully!"
        redirect_to @kitten
      else
        flash[:alert] = "There was an error updating the kitten."
        render :edit
      end
    end
  
    def destroy
      @kitten.destroy
      flash[:notice] = "Kitten deleted successfully!"
      redirect_to kittens_path
    end
  
    private
  
    def set_kitten
      @kitten = Kitten.find(params[:id])
    end
  
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with(model: @kitten, local: true) do |form| %>
    <% if @kitten.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this kitten from being saved:</h2>
        <ul>
          <% @kitten.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :age %>
      <%= form.number_field :age %>
    </div>
  
    <div class="field">
      <%= form.label :cuteness %>
      <%= form.number_field :cuteness %>
    </div>
  
    <div class="field">
      <%= form.label :softness %>
      <%= form.number_field :softness %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/kittens/edit.html.erb
<h1><%= @kitten.new_record? ? 'New Kitten' : 'Edit Kitten' %></h1>
<%= render 'form' %>
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<%= link_to 'New Kitten', new_kitten_path %>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= kitten.name %> (<%= kitten.age %> years old)
      <%= link_to 'Show', kitten %> |
      <%= link_to 'Edit', edit_kitten_path(kitten) %> |
      <%= link_to "Delete", kitten, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1><%= @kitten.new_record? ? 'New Kitten' : 'Edit Kitten' %></h1>
<%= render 'form' %>
<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %> years old</p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Back to All Kittens', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Display flash messages -->
    <% if flash[:success] %>
      <div class="flash success">
        <%= flash[:success] %>
      </div>
    <% elsif flash[:error] %>
      <div class="flash error">
        <%= flash[:error] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>